console.log('Résultat du tournoi de Mario Kart');
console.log('**********************************');
console.log('Prendre le post-it sur la table');
console.log('Lire la première ligne');
console.log('regarder le classement');
console.log('regarder le personnage concerné');
console.log('regarder le nombre de point par rapport au classement');
console.log('Affecter les points au personnage dans le tableau de résultats');
console.log('Lire la ligne suivante');
console.log('regarder le classement');
console.log('regarder le personnage concerné');
console.log('regarder le nombre de point par rapport au classement');
console.log('Affecter les points au personnage');
console.log('Lire la ligne suivante');
console.log('regarder le classement');
console.log('regarder le personnage concerné');
console.log('regarder le nombre de point par rapport au classement');
console.log('Affecter les points au personnage');
console.log('Lire la ligne suivante');
console.log('regarder le classement');
console.log('regarder le personnage concerné');
console.log('regarder le nombre de point par rapport au classement');
console.log('Affecter les points au personnage');
console.log('Lire la ligne suivante');
console.log('regarder le classement');
console.log('regarder le personnage concerné');
console.log('regarder le nombre de point par rapport au classement');
console.log('Affecter les points au personnage');
console.log('Lire la ligne suivante');
console.log('regarder le classement');
console.log('regarder le personnage concerné');
console.log('regarder le nombre de point par rapport au classement');
console.log('Affecter les points au personnage');
console.log('Regarder le personnage qui a le plus de points');
console.log('Afficher le gagnant !!');